# -*- coding: utf-8 -*-
"""Guia de estudo: fisiopatologia hematológica (plaquetas, CID, anemias, policitemia).

Fonte: PDF "Guia de estudo transversal de fisiopatologia hematológica" (enviado
pelo usuário, texto em work/fonte.md). Perfil de aula, pt-BR, paleta UCP, sem imagens.
"""

COURSE_INFO = {'course': 'Fisiopatologia hematológica', 'institution': '', 'author': ''}

CONFIG = {
    'PALETTE': 'ucp',
    'LANG': 'pt-BR',
    'PROFILE': 'lecture',
    'IMAGES': {'mode': 'web-only', 'max_n': 4,
               'allow_ai': False, 'allow_placeholder': False},
    'SHOW_FOOTER': True,
    'SHOW_SLIDE_NUMBER': True,
    'ALLOW_TERMS': [],
}

SLIDES = [
    # 1 — capa
    {'module': 'title',
     'title': 'Fisiopatologia hematológica: plaquetas, coagulação e anemias',
     'subtitle': 'Guia de estudo: distúrbios plaquetários, CID, eritrócitos e anemias',
     'course': 'Fisiopatologia hematológica'},

    # 2 — bloco 1: plaquetas
    {'module': 'section_divider',
     'section_title': 'Distúrbios plaquetários e hemostasia primária',
     'section_subtitle': 'Trombocitopenia, trombocitopatia e os mecanismos de destruição plaquetária.'},

    {'module': 'definition',
     'kicker': 'Trombocitopenia',
     'title': 'Definição e três vias de redução',
     'image': 'imagens/trombocitopenia_vias_v2.png',
     'caption': 'Cada compartimento reduz a contagem por uma via própria: produção, sequestro ou destruição.',
     'credit': 'Ilustração esquemática gerada por IA, apoio visual',
     'main_statement': 'Trombocitopenia é a contagem de plaquetas periféricas abaixo de 150.000/µL, '
                       'causada por produção medular insuficiente, sequestro esplênico ou destruição acelerada.',
     'elaboration': 'As três vias atuam isoladas ou combinadas; a classificação seguinte separa as '
                    'etiologias pelo compartimento lesado.',
     'key_points': [
         {'title': 'Produção reduzida',
          'desc': 'Megacariócitos suprimidos por aplasia, infiltração neoplásica, HIV ou citotóxicos.'},
         {'title': 'Destruição acelerada',
          'desc': 'Mecanismos imunes ou agressão mecânica microvascular consomem plaquetas além da reposição.'}]},

    {'module': 'taxonomy_tree',
     'kicker': 'Classificação',
     'title': 'Etiologias pelo compartimento lesado',
     'root': 'Trombocitopenia',
     'categories': [
         {'name': 'Medula óssea',
          'property': 'Produção insuficiente de megacariócitos',
          'examples': ['Aplasia medular por falência de células-tronco',
                       'Leucemia ou metástases infiltrativas',
                       'HIV, quimioterapia e radioterapia']},
         {'name': 'Baço',
          'property': 'Sequestro e represamento de plaquetas',
          'examples': ['Esplenomegalia retém até 90% das plaquetas',
                       'Baço normal retém de 30% a 40% da massa']},
         {'name': 'Circulação',
          'property': 'Sobrevida diminuída de origem não imunitária',
          'examples': ['Próteses valvares fragmentam plaquetas por cisalhamento',
                       'Hipertensão maligna e fibrina fragmentam plaquetas e eritrócitos',
                       'CIVD e púrpura trombocitopênica trombótica consomem plaquetas']}]},

    {'module': 'stat_card',
     'kicker': 'Sequestro esplênico',
     'title': 'Plaquetopenia sem falha de produção',
     'image': 'imagens/baco_sequestro.png',
     'caption': 'Baço aumentado retém a maior parte das plaquetas, com fluxo de saída reduzido.',
     'credit': 'Ilustração esquemática gerada por IA, apoio visual',
     'stat_num': '90%',
     'stat_title': 'das plaquetas periféricas podem ser sequestradas por baço aumentado, '
                   'com plaquetopenia dilucional aparente.',
     'narrative_blocks': [
         {'title': 'Baço normal',
          'desc': 'Retém entre 30% e 40% da massa de plaquetas antes da liberação para a circulação.'},
         {'title': 'Leitura do exame',
          'desc': 'A contagem cai, mas a medula continua produzindo. O problema está na distribuição.'}]},

    {'module': 'timeline',
     'kicker': 'Fármacos',
     'title': 'Cinética da trombocitopenia induzida por fármacos',
     'milestones': [
         {'label': '2 a 3 dias', 'title': 'Reexposição',
          'desc': 'A memória imunológica dispara queda abrupta da contagem plaquetária.'},
         {'label': '7 dias ou mais', 'title': 'Primeira exposição',
          'desc': 'Janela necessária para a síntese de anticorpos antes da queda plaquetária.'},
         {'label': 'Após suspensão', 'title': 'Recuperação',
          'desc': 'Descontinuar o fármaco causador restaura rapidamente os níveis plaquetários normais.'}]},

    {'module': 'flow_diagram',
     'kicker': 'PTI',
     'title': 'Mecanismo da destruição imune',
     'explanation': 'A perda de autotolerância inicia a cadeia; a fagocitose esplênica é o desfecho '
                    'que reduz a contagem.',
     'steps': [
         {'label': '1', 'title': 'Autotolerância',
          'desc': 'Linfócitos T auxiliares CD4 e T reguladores falham e perdem a autotolerância.'},
         {'label': '2', 'title': 'Autoanticorpos',
          'desc': 'Anticorpos opsonizam GPIIb/IIIa e GPIb/IX da membrana plaquetária.',
          'highlight': True},
         {'label': '3', 'title': 'Reconhecimento',
          'desc': 'Macrófagos do baço reconhecem plaquetas e eritrócitos opsonizados.'},
         {'label': '4', 'title': 'Fagocitose',
          'desc': 'Fagocitose acelerada reduz a contagem; a trombopoietina permanece baixa ou normal.'}]},

    {'module': 'side_by_side',
     'kicker': 'PTI',
     'title': 'PTI primária ou secundária?',
     'left_card': {'header': 'PTI primária', 'title': 'Doença idiopática',
                   'points': ['Surge sem fator desencadeante ou doença prévia.',
                              'Autoanticorpos antiplaquetários com depuração excessiva pelo baço.',
                              'Doença autoimune de origem idiopática.']},
     'right_card': {'header': 'PTI secundária', 'title': 'Gatilho clínico identificável',
                    'points': ['Associada a HIV, lúpus eritematoso sistêmico e síndrome antifosfolípide.',
                               'Inclui leucemia linfocítica crônica, hepatite C e heparina.',
                               'Mesma base imune da forma primária: autoanticorpos e fagocitose.']}},

    {'module': 'side_by_side',
     'kicker': 'Plaquetas',
     'title': 'Déficit quantitativo ou qualitativo?',
     'left_card': {'header': 'Trombocitopenia', 'title': 'Déficit numérico',
                   'points': ['Contagem abaixo de 150.000/µL no sangue periférico.',
                              'Petéquias surgem somente quando há deficiência quantitativa.',
                              'Pode resultar de produção, sequestro ou destruição.']},
     'right_card': {'header': 'Trombocitopatia', 'title': 'Déficit funcional',
                    'points': ['Contagem celular basal frequentemente normal.',
                               'Ácido acetilsalicílico acetila a ciclo-oxigenase de forma irreversível.',
                               'Outros AINEs inibem a ciclo-oxigenase só enquanto o fármaco circula.']}},

    # bloco 2: coagulopatias e vasos
    {'module': 'section_divider',
     'section_title': 'Coagulopatias e integridade vascular',
     'section_subtitle': 'Sangramentos profundos após trauma ou cirurgia, e vasos frágeis por causa estrutural.'},

    {'module': 'comparison_table',
     'kicker': 'Coagulopatias',
     'title': 'Coagulopatias hereditárias',
     'takeaway': 'A doença de von Willebrand compromete a adesão plaquetária e o carreador do fator VIII.',
     'headers': ['Doença', 'Defeito', 'Característica'],
     'col_widths': [1.0, 1.4, 1.6],
     'rows': [['Doença de von Willebrand', 'Adesão plaquetária e carreador do fator VIII',
               'Coagulopatia hereditária mais prevalente'],
              ['Hemofilia A', 'Deficiência do fator VIII', 'Congênita, funcional ou quantitativa'],
              ['Hemofilia B', 'Deficiência do fator IX', 'Deficiência congênita do fator IX']]},

    {'module': 'fixed_schema_card',
     'kicker': 'Integridade vascular',
     'title': 'Quatro causas de fragilidade capilar',
     'fields': [
         {'label': 'Telangiectasia hereditária',
          'value': 'Transtorno autossômico com capilares e arteríolas dilatadas de paredes delgadas.'},
         {'label': 'Escorbuto',
          'value': 'Deficiência de vitamina C: colágeno defeituoso impede o cimentamento endotelial.'},
         {'label': 'Doença de Cushing',
          'value': 'Hipercortisolismo causa catabolismo proteico e perda do suporte perivascular.'},
         {'label': 'Púrpura senil',
          'value': 'Envelhecimento reduz o colágeno dérmico e causa equimoses fáceis nos idosos.'}]},

    # bloco 3: CID
    {'module': 'section_divider',
     'section_title': 'Coagulação intravascular disseminada [CID]',
     'section_subtitle': 'Ativação desregulada da coagulação que consome a reserva hemostática e causa hemorragia.'},

    {'module': 'flow_diagram',
     'kicker': 'CID',
     'title': 'Cascata da coagulação intravascular',
     'explanation': 'A trombina descontrolada gera trombose e consumo; a plasmina gera PDF que sustenta a hemorragia.',
     'steps': [
         {'label': '1', 'title': 'Gatilho',
          'desc': 'Fator tecidual de placenta, tumores ou queimaduras, além de sepse e choque, ativa a coagulação.'},
         {'label': '2', 'title': 'Trombina',
          'desc': 'Geração descontrolada de trombina forma microtrombos de fibrina na microcirculação.',
          'highlight': True},
         {'label': '3', 'title': 'Consumo',
          'desc': 'Fatores V, VIII, fibrinogênio e plaquetas se esgotam; redes de fibrina rompem eritrócitos.'},
         {'label': '4', 'title': 'Hemorragia',
          'desc': 'A plasmina gera PDF, que inibe a trombina e a agregação plaquetária.'}]},

    # bloco 4: eritrócitos e anemias
    {'module': 'section_divider',
     'section_title': 'Eritrócitos e classificação das anemias',
     'section_subtitle': 'Eritropoiese, valores de referência e os critérios que separam os tipos de anemia.'},

    {'module': 'cycle_diagram',
     'kicker': 'Eritrócito',
     'title': 'Ciclo de produção e destruição',
     'center_label': 'Eritrócito',
     'nodes': [
         {'title': 'Sensor renal',
          'desc': 'Queda da pressão tecidual de oxigênio estimula a secreção de eritropoietina.'},
         {'title': 'Medula óssea',
          'desc': 'A eritropoietina acelera a liberação de reticulócitos a partir de progenitores.'},
         {'title': 'Circulação',
          'desc': 'Vida útil média de 120 dias, com depuração basal de 1% ao dia.', 'highlight': True},
         {'title': 'Macrófagos',
          'desc': 'Baço, fígado e medula fagocitam hemácias senescentes e clivam a globina.'},
         {'title': 'Reaproveitamento',
          'desc': 'O ferro retorna à medula; o anel porfirínico vira bilirrubina não conjugada.'}]},

    {'module': 'comparison_table',
     'kicker': 'Laboratório',
     'title': 'Valores de referência eritrocitários',
     'takeaway': 'Hemoglobina e hematócrito variam por sexo; VCM e reticulócitos têm a mesma faixa.',
     'headers': ['Parâmetro', 'Homens', 'Mulheres', 'Significado'],
     'col_widths': [1.6, 1.0, 1.0, 2.4],
     'rows': [['Hemoglobina [g/dL]', '14,0 a 16,5', '12,0 a 15,0', 'Carreador total de oxigênio no sangue'],
              ['Hematócrito [%]', '40 a 50', '37 a 47', 'Fração do volume globular em 100 mL'],
              ['VCM [fL]', '85 a 100', '85 a 100', 'Tamanho médio de cada eritrócito'],
              ['Reticulócitos [%]', '1,0 a 1,5', '1,0 a 1,5', 'Capacidade de produção da medula']]},

    {'module': 'definition',
     'kicker': 'Anemia',
     'title': 'Anemia limita a entrega de oxigênio',
     'image': 'imagens/curva_hemoglobina_v2.png',
     'caption': 'Curva deslocada à direita libera mais oxigênio em pressões tissulares baixas.',
     'credit': 'Gráfico esquemático gerado por IA, apoio visual',
     'main_statement': 'Anemia é a redução anormal de hemoglobina e eritrócitos circulantes, '
                       'que limita a entrega tecidual de oxigênio.',
     'elaboration': 'O organismo responde com três eixos: maior cedência tecidual, redistribuição do '
                    'fluxo e aumento do débito cardíaco.',
     'key_points': [
         {'title': 'Cedência tecidual',
          'desc': 'A hemoglobina desvia a curva de dissociação para liberar mais oxigênio aos tecidos.'},
         {'title': 'Redistribuição',
          'desc': 'Vasoconstrição na pele e nos rins preserva miocárdio e sistema nervoso central.'},
         {'title': 'Débito cardíaco',
          'desc': 'Com hemoglobina abaixo de 100 g/L, o débito sobe; hipóxia miocárdica causa angina.'}]},

    {'module': 'side_by_side',
     'kicker': 'Classificação',
     'title': 'Regenerativa ou arregenerativa?',
     'left_card': {'header': 'Anemia regenerativa', 'title': 'Medula íntegra responde',
                   'points': ['Reticulocitose acima de 1,5%.',
                              'Medula íntegra eleva a produção em perdas agudas.',
                              'Causada por hemorragia aguda profusa ou anemias hemolíticas.']},
     'right_card': {'header': 'Anemia arregenerativa', 'title': 'Medula incapaz de responder',
                    'points': ['Reticulocitopenia ou contagem baixa para o grau de anemia.',
                               'Medula sem resposta por esgotamento ou supressão.',
                               'Causada por carência de ferro, B12 ou folato, aplasia e neoplasia.']}},

    {'module': 'taxonomy_tree',
     'kicker': 'Morfometria',
     'title': 'Classificação pelo VCM',
     'root': 'Anemias',
     'categories': [
         {'name': 'Microcíticas',
          'property': 'VCM abaixo de 83 fL',
          'examples': ['Anemia ferropriva e talassemia',
                       'Anemia sideroblástica, intoxicação por chumbo ou alumínio',
                       'Anemia de doenças crônicas']},
         {'name': 'Normocíticas',
          'property': 'VCM de 83 a 97 fL',
          'examples': ['Hemólise aguda e aplasia medular inicial',
                       'Hemorragia aguda recente',
                       'Anemia de doenças crônicas']},
         {'name': 'Macrocíticas',
          'property': 'VCM acima de 97 fL',
          'examples': ['Megaloblásticas por deficiência de B12 ou folato',
                       'Etilismo, hepatopatias crônicas e síndrome mielodisplásica',
                       'Hipotireoidismo e reticulocitose intensa']}]},

    # bloco 5: hemolíticas
    {'module': 'section_divider',
     'section_title': 'Anemias hemolíticas',
     'section_subtitle': 'Destruição prematura de hemácias, com reticulocitose compensatória e VCM normal.'},

    {'module': 'side_by_side',
     'kicker': 'Hemólise',
     'title': 'Intravascular ou extravascular?',
     'left_card': {'header': 'Hemólise intravascular', 'title': 'Ruptura dentro da circulação',
                   'points': ['Eritrócitos rompem diretamente dentro da circulação.',
                              'Complemento em transfusão incompatível, toxinas ou cisalhamento.',
                              'Hemoglobinemia livre, hemoglobinúria e hemossiderinúria renal.']},
     'right_card': {'header': 'Hemólise extravascular', 'title': 'Fagocitose esplênica',
                    'points': ['Macrófagos do baço fagocitam hemácias que perderam deformabilidade.',
                               'Icterícia por bilirrubina não conjugada e esplenomegalia.',
                               'Sem hemoglobinúria.']}},

    {'module': 'case_block',
     'kicker': 'Esferocitose',
     'title': 'Esferocitose hereditária',
     'image': 'imagens/esferocito_vs_disco_v2.png',
     'caption': 'Esferócito sem palidez central perde a forma de disco e fica rígido.',
     'credit': 'Ilustração esquemática gerada por IA, apoio visual',
     'case_stem': 'Anomalia autossômica dominante da membrana eritrocitária. A perda de fragmentos '
                  'de membrana converte o eritrócito em esferócito rígido.',
     'reasoning': 'Sem flexibilidade, os esferócitos ficam retidos no baço e são fagocitados '
                  'prematuramente. A tríade é anemia leve, icterícia e esplenomegalia.',
     'diagnosis': 'Esferocitose hereditária',
     'clinical_pearl': 'A esplenectomia remove o principal sítio de destruição; a infecção por parvovírus B19 pode causar crise aplásica.',
     'findings': ['Anemia hemolítica crônica leve',
                  'Icterícia e esplenomegalia',
                  'Cálculos de bilirrubina pigmentar']},

    {'module': 'flow_diagram',
     'kicker': 'Hemoglobinopatia',
     'title': 'Vaso-oclusão na doença falciforme',
     'explanation': 'Crises dolorosas e síndrome torácica aguda são as complicações mais graves; a síndrome '
                    'torácica é a principal causa de óbito.',
     'steps': [
         {'label': '1', 'title': 'Mutação',
          'desc': 'Valina substitui o ácido glutâmico na cadeia beta da hemoglobina.'},
         {'label': '2', 'title': 'Polimerização',
          'desc': 'Desoxi-HbS forma gel semissólido sob hipóxia, desidratação ou acidose.',
          'highlight': True},
         {'label': '3', 'title': 'Falcização',
          'desc': 'O citoesqueleto enrijece e a célula vira foice; a lesão de membrana torna-se permanente.'},
         {'label': '4', 'title': 'Oclusão',
          'desc': 'Hemácias rígidas aderem ao endotélio e bloqueiam a microcirculação terminal.'}]},

    # bloco 6: produção medular
    {'module': 'section_divider',
     'section_title': 'Anemias por insuficiência de produção medular',
     'section_subtitle': 'Ferro, vitaminas e falência de precursores reduzem a produção de hemácias.'},

    {'module': 'fixed_schema_card',
     'kicker': 'Ferropriva',
     'title': 'Quem perde ou demanda mais ferro',
     'footnote': 'Absorção diária necessária: 1 mg a 2 mg de ferro, para suprir a perda fecal.',
     'fields': [
         {'label': 'Adultos',
          'value': 'Perda crônica oculta por úlcera, pólipos, hemorroidas ou câncer colorretal.'},
         {'label': 'Mulheres em idade fértil',
          'value': 'Menorragia e perdas menstruais abundantes.'},
         {'label': 'Gestantes',
          'value': 'Crescimento fetal e expansão da volemia aumentam a demanda basal.'},
         {'label': 'Lactentes',
          'value': 'Leite de vaca não fortificado tem baixa biodisponibilidade de ferro.'}]},

    {'module': 'comparison_table',
     'kicker': 'Megaloblástica',
     'title': 'Vitamina B12 versus ácido fólico',
     'takeaway': 'A neuropatia distingue a B12; o folato causa macrocitose sem dano aos cordões espinais.',
     'headers': ['Critério', 'Vitamina B12', 'Ácido fólico'],
     'col_widths': [1.2, 2.0, 2.0],
     'rows': [['Mecanismo', 'Cofator na síntese de DNA e no metabolismo de ácidos graxos neuronais',
               'Cofator na síntese de purinas e DNA'],
              ['Lesão neurológica', 'Desmielinização dos cordões posteriores e laterais',
               'Ausente'],
              ['Causas principais', 'Anemia perniciosa, gastrectomia, ressecção ileal e metformina',
               'Desnutrição, etilismo, doença celíaca e metotrexato']]},

    {'module': 'taxonomy_tree',
     'kicker': 'Aplasia',
     'title': 'Formas da anemia aplásica',
     'root': 'Anemia aplásica',
     'categories': [
         {'name': 'Adquiridas',
          'property': 'Falência após agressão ou de causa idiopática',
          'examples': ['Idiopática autoimune, cerca de 65% dos diagnósticos',
                       'Benzeno, cloranfenicol, quimioterapia e radiação ionizante',
                       'Hepatite seronegativa, mononucleose e HIV']},
         {'name': 'Hereditárias',
          'property': 'Falência por defeito genético',
          'examples': ['Anemia de Fanconi: rádios, polegares e baixa estatura',
                       'Mutações nos complexos enzimáticos da telomerase']}]},

    # bloco 7: policitemia
    {'module': 'comparison_table',
     'kicker': 'Policitemia',
     'title': 'Três tipos de policitemia',
     'takeaway': 'Hematócrito acima de 50% eleva a viscosidade do sangue e predispõe a eventos trombóticos.',
     'headers': ['Critério', 'Relativa', 'Primária', 'Secundária'],
     'col_widths': [1.1, 1.4, 1.4, 1.4],
     'rows': [['Mecanismo', 'Contração do volume plasmático',
               'Neoplasia mieloproliferativa clonal, com panmielose',
               'Eritropoietina estimulada por hipóxia ou secreção ectópica'],
              ['Causas', 'Desidratação, diuréticos, diarreia e vômitos',
               'Mutação somática JAK2 V617F ou no éxon 12',
               'Altitude, DPOC, cardiopatia cianótica, tabagismo ou isquemia renal'],
              ['Diagnóstico-chave', 'Hematócrito alto com volume plasmático reduzido',
               'Critérios maiores e menor da OMS', 'Causa hipóxica identificável']]},

    # bloco 8: revisão
    {'module': 'glossary',
     'kicker': 'Revisão',
     'title': 'Termos-chave do guia',
     'terms': [
         {'term': 'Megacariócito', 'def': 'Célula da medula óssea que origina as plaquetas.'},
         {'term': 'Opsonização', 'def': 'Revestimento de plaquetas ou hemácias por anticorpos, que sinaliza fagocitose.'},
         {'term': 'Tromboxano A2', 'def': 'Mediador da agregação plaquetária, bloqueado pelo ácido acetilsalicílico.'},
         {'term': 'Trombopoietina', 'def': 'Hormônio que estimula a produção de plaquetas na medula óssea.'},
         {'term': 'CID', 'def': 'Ativação desregulada da coagulação, com consumo de fatores e hemorragia.'},
         {'term': 'PDF', 'def': 'Produtos de degradação da fibrina, que inibem a trombina e a agregação.'},
         {'term': 'Eritropoietina', 'def': 'Hormônio renal que acelera a produção de eritrócitos sob hipóxia.'},
         {'term': 'Reticulócito', 'def': 'Eritrócito jovem; sua taxa indica a capacidade de produção medular.'}]},
]
